---
title: "MLB Write Up"
author: "Jake Esprabens"
date: "7/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Collection

### Google hits
In order to measure the bandwagon level of MLB fans, we gathered data from google trends to depict the popularity of each team.  This data was gathered using the [**gtrendsR**](https://cran.r-project.org/web/packages/gtrendsR/gtrendsR.pdf) package, which automatically pulls the data from [Google Trends](https://trends.google.com/trends/?geo=US) API.  The units of the Google Trend data are relative to the maximum of the trend.  Therefore, we went through each team and determined that the Chicago Cubs had the maximum google trend hits; this lead us to gather data for the rest of the MLB teams relative to the Cubs.

### Sports Betting Odds
The preseason odds dataset was gathered using data from [Sports Odds History](https://www.sportsoddshistory.com/mlb-odds/).  We compiled this data by viewing each teams' odds of winning the World Series from 2004 to the present.  Ideally, we would have like to use monthly odds of winning the World Series for each MLB team; however, this data was not available for every desired year.

### Attendance and Payroll
We decided that attendence and payroll of each team by season may be valuable exogenous variables that could help determine when fans would become bandwagons.  We gathered this data from [Baseball Reference](https://www.baseball-reference.com/leagues/MLB/2019-misc.shtml) by copying the data from each the years 2004 to 2019.

### Team Performance
Other exogenous variables we decided would be a valuable predictor in this model was win percentage and whether each team made the playoffs.  We were able to download this data directly from [Sean Lahman's Baseball Database](http://www.seanlahman.com/baseball-archive/statistics/).  This dataset was also filled with other variables such as attendance along with indicators of whether each team won their respective divisions, wild card games, leagues, and the world series.

### TV Market Size
The TV Market Size of each team is was also important to create an accurate estimation of the number of true fans of each.  We were able to gather this data using the Nielsen Market Size from [Sports Media Watch](https://www.sportsmediawatch.com/nba-market-size-nfl-mlb-nhl-nielsen-ratings/).  

